class ClassA:
	public getClass() :: class reference:
		return class of self

class ClassB:
	public getClass() :: class reference:
		return class of self

class Comparison:
	public int: integer
	public str: string
		

test "ClassySK - Compare":
	set {_a1} to new instance of ClassA
	set {_a2} to new instance of ClassA

	set {_b} to new instance of ClassB

	assert class of {_a1} is class of {_a2}

	assert class of {_a1} is class ClassA

	assert {_a1} is an instance of ClassA
	assert {_a2} is an instance of ClassA

	assert class of {_a1} is {_a1}::getClass()

	assert class of {_a1} is not class of {_b}

	assert {_a1} is not an instance of ClassB

	assert {_b} is an instance of ClassB
	assert class of {_b} is class named ClassB

	assert class of {_b} is {_b}::getClass()

	set {_a} to new instance of Comparison:
		int: 1
		str: "a"

	set {_b} to new instance of Comparison:
		int: 1
		str: "a"

	assert {_a} is {_a}

	assert typed {_a} is {_a}
	assert {_a} is typed {_a}
	assert typed {_a} is typed {_a}
	assert {_a} is untyped {_a}

	assert {_a} is not {_b}
	assert typed {_a} is not typed {_b}
	assert untyped {_a} is not untyped {_b}
	assert typed {_a} is not {_b}
	assert {_a} is not typed {_b}