class ClassA:
	public getClass() :: class reference:
		return class of self

class ClassB:
	public getClass() :: class reference:
		return class of self

class ClassC extends ClassA:


test "ClassySK - Compare":
	set {_a1} to new instance of ClassA
	set {_a2} to new instance of ClassA

	set {_b} to new instance of ClassB

	assert class of {_a1} is class of {_a2}

	assert class of {_a1} is class ClassA

	assert {_a1} is an instance of ClassA
	assert {_a2} is an instance of ClassA

	assert class of {_a1} is {_a1}::getClass()

	assert class of {_a1} is not class of {_b}

	assert {_a1} is not an instance of ClassB

	assert {_b} is an instance of ClassB
	assert class of {_b} is class named ClassB

	assert class of {_b} is {_b}::getClass()

	set {_C} to new instance of ClassC

	assert {_C} is an instance of ClassA
	assert {_C} is not an exact instance of ClassA
	assert (whether {_C} is an exact instance of ClassA) is not true