class TestConstruct:
	public int: integer
	public intDefault: integer = 1
	private intPrivate: integer

	public str: string
	public strPrivate: string

	public static staticField: boolean

	public static createAll() :: class instance:
		set {_instance} to new instance of TestConstruct:
			int: 1
			intDefault: 2
			intPrivate: 3

			str: "test"
			strPrivate: "testPrivate"

		return {_instance}

	public checkPrivate() :: boolean:
		if self::intPrivate is 3:
			self::strPrivate is "testPrivate"
			return true

		return false


test "ClassySK - Constructors":
	set {_test} to new instance of TestConstruct
	assert {_test} is an instance of TestConstruct

	delete {_test}

	set {_test} to new instance of TestConstruct:
		int: 1
		intDefault: 2

	assert {_test}::int is 1
	assert {_test}::intDefault is 2

	set {_test} to new instance of TestConstruct:
		int: 3

	assert {_test}::int is 3
	assert {_test}::intDefault is 1

	parse:
		set {_test} to new instance of TestConstruct:
			int: 1
			intPrivate: 3
	assert last parse logs is set with "Attempt to set private field from external constructor"

	set {_instance} to TestConstruct::createAll()
	assert {_instance}::int is 1
	assert {_instance}::intDefault is 2

	assert {_instance}::str is "test"
	assert {_instance}::checkPrivate() is true

	parse:
		set {_instance} to new instance of TestConstruct:
			staticField: true
	assert last parse logs is set with "Attempt to set static field in constructor"
