class TestFields:
	private privateField: string = "im private"
	public publicField: string = "im public"

	public static publicStaticField: string = "im public and static"
	private static privateStaticField: string = "im private and static"

test "ClassySK - Fields":
	set {_instance} to new instance of TestFields

	assert {_instance}::publicStaticField is not set with "Attempt to access static field from instance"
	assert TestFields::publicStaticField is "im public and static" with "public access (static)"
	parse:
		set {_var} to TestFields::privateStaticField
	assert last parse logs is set with "Attempt to access private field from outside class structure (static)"
	parse:
		set {_var} to TestFields::publicField
	assert last parse logs is set with "Attempt to access instance field from static context"
	
	assert {_instance}::publicField is "im public" with "public access (instance)"
	assert {_instance}::privateField is not set with "Attempt to access private field from outside class structure (instance)"