class TestFields:
	private privateField: string = "im private"
	public publicField: string = "im public"

	public static publicStaticField: string = "im public and static"
	private static privateStaticField: string = "im private and static"

test "ClassySK - Field Access":
	set {_instance} to new instance of TestFields

	parse:
		set {_} to {_instance}<TestFields>::publicStaticField

	assert last parse logs is set with "Attempt to access static field from instance"

	assert TestFields::publicStaticField is "im public and static" with "public access (static)"
	parse:
		set {_var} to TestFields::privateStaticField
	assert last parse logs is set with "Attempt to access private field from outside class structure (static)"
	parse:
		set {_var} to TestFields::publicField
	assert last parse logs is set with "Attempt to access instance field from static context"
	
	assert {_instance}::publicField is "im public" with "public access (instance)"
	parse:
		set {_} to {_instance}<TestFields>::privateField

	assert last parse logs is set with "Attempt to access private field from outside class structure (instance)"

	parse:
		set {_} to {_instance}<TestFields>::privateField
	assert last parse logs is set with "Attempt to access private field from outside class structure (instance)"

class TestTyped:
	public intField: integer
	public strField: string
	public objField: object
	public numField: number

	public static static_intField: integer
	public static static_strField: string
	public static static_objField: object
	public static static_numField: number

test "ClassySK - Typed Fields":
	set {_instance} to new instance of TestTyped

	# int
	set {_instance}::intField to 1
	assert {_instance}::intField is 1 with "Set int field to 1"
	set {_instance}::intField to 1.5
	assert {_instance}::intField is 1 with "Attempt set int field to float"

	# str
	set {_instance}::strField to "test"
	assert {_instance}::strField is "test" with "Set string field to string"
	set {_instance}::strField to 1
	assert {_instance}::strField is "test" with "Attempt set string field to int"

	# obj
	set {_instance}::objField to "test"
	assert {_instance}::objField is "test" with "Set object field to string"
	set {_instance}::objField to 1
	assert {_instance}::objField is 1 with "Set object field to int"
	set {_instance}::objField to 1.5
	assert {_instance}::objField is 1.5 with "Set object field to float"
	set {_instance}::objField to true
	assert {_instance}::objField is true with "Set object field to boolean"

	# num
	set {_instance}::numField to 1.5
	assert {_instance}::numField is 1.5 with "Set num field to float"
	set {_instance}::numField to 1
	assert {_instance}::numField is 1 with "Set num field to int"
	set {_instance}::numField to "test"
	assert {_instance}::numField is 1 with "Attempt Set num field to string"
	
test "ClassySK - Typed Static Fields":

	# int
	set TestTyped::static_intField to 1
	assert TestTyped::static_intField is 1 with "Set int field to 1"

	# acceptChange does not care about int/number distinction, should be caught at runtime by canConvert
	set TestTyped::static_intField to 1.5
	assert TestTyped::static_intField is 1 with "Attempt set int field to float"

	# str
	set TestTyped::static_strField to "test"
	assert TestTyped::static_strField is "test" with "Set string field to string"
	parse:
		set TestTyped::static_strField to 1
	assert last parse logs is set with "Attempt set string field to int"

	# obj
	set TestTyped::static_objField to "test"
	assert TestTyped::static_objField is "test" with "Set object field to string"
	set TestTyped::static_objField to 1
	assert TestTyped::static_objField is 1 with "Set object field to int"
	set TestTyped::static_objField to 1.5
	assert TestTyped::static_objField is 1.5 with "Set object field to float"
	set TestTyped::static_objField to true
	assert TestTyped::static_objField is true with "Set object field to boolean"

	# num
	set TestTyped::static_numField to 1.5
	assert TestTyped::static_numField is 1.5 with "Set num field to float"
	set TestTyped::static_numField to 1
	assert TestTyped::static_numField is 1 with "Set num field to int"
	parse:
		set TestTyped::static_numField to "test"
	assert last parse logs is set with "Attempt Set num field to string"

class TestDefaults:
	public intField: integer = 1
	public numField: number = 1.5
	public strField: string = "test"
	public boolField: boolean = true
	public objField: object = "test"

	public intsField: integers = 1, 2, 3, 4
	public numsField: numbers = 1, 2.5, 3.1, 4
	public strsField: strings = "test", "hello"
	public boolsField: booleans = true, false
	public objsField: objects = 1, 1.4, "test", true

parse:
	results: {-testInvalidDefaults::*}
	code:
		class TestInvalidDefaults:
			public intField: integer = true
			public numField: number = "not a number"
			public strField: string = 1
			public boolField: boolean = 1

			public intsField: integers = 1, 2, 3, 4 and true
			public numsField: numbers = 1, 2.5, 3.1, 4 and true
			public strsField: strings = "test", "hello" and true
			public boolsField: booleans = true, false and 1

			public singleNumField: number = 1, 2, 3 and 4

test "ClassySK - Default Field Values":
	set {_instance} to new instance of TestDefaults

	assert {_instance}::intField is 1
	assert {_instance}::numField is 1.5
	assert {_instance}::strField is "test"
	assert {_instance}::boolField is true
	assert {_instance}::objField is "test"

	assert {_instance}::intsField is 1, 2, 3, 4
	assert {_instance}::numsField is 1, 2.5, 3.1, 4
	assert {_instance}::strsField is "test", "hello"
	assert {_instance}::boolsField is true, false
	assert {_instance}::objsField is 1, 1.4, "test", true

	assert size of {-testInvalidDefaults::*} is 9

class TestChangers:
	public static intsField: integers = 2, 1
	public static intField: integer = 1
	public static strField: string = "test"
	public static strsField: strings = "test"
	public static intObjField: object = 1
	public static strObjField: object = "test"

	public testInvalidChanger: integer = 1

	public testReset: numbers = 1, 2

test "ClassySK - Changers & Arithmetic":
	add 1 to TestChangers::intsField
	add 1 to TestChangers::intField

	add "test" to TestChangers::strField
	add "test" to TestChangers::strsField

	add 1 to TestChangers::intObjField
	add "test" to TestChangers::strObjField

	assert TestChangers::intsField is 2, 1, 1
	assert TestChangers::intField is 2

	assert TestChangers::strField is "testtest"
	assert TestChangers::strsField is "test", "test"

	assert TestChangers::intObjField is 2
	assert TestChangers::strObjField is "testtest"

	remove 2 from TestChangers::intsField
	remove 2 from TestChangers::intField
	remove 2 from TestChangers::intObjField

	assert TestChangers::intsField is 1, 1
	assert TestChangers::intField is 0
	assert TestChangers::intObjField is 0

	set {_instance} to new instance of TestChangers

	add 0.5 to {_instance}::testInvalidChanger
	assert {_instance}::testInvalidChanger is 1

	set {_instance}::testReset to 5
	reset {_instance}::testReset
	assert {_instance}::testReset is 1, 2