using error catching

class TestSuppressErrors:
	options:
		suppress runtime errors: true

	private privateField: string
	public stringField: string

	private privateMethod():
		broadcast true

	public stringArg(str: string):
		broadcast {_str}

test "ClassySK - Suppress Runtime Errors":
	set {_instance} to new instance of TestSuppressErrors

	catch runtime errors:
		set {_test} to {_instance}::nonExistingField
		set {_test} to {_instance}::privateField
		set {_instance}::stringField to 1
		{_instance}::privateMethod()
		{_instance}::nonExistingMethod()
		{_instance}::stringArg(true)

	assert last caught runtime errors is not set