using error catching

class TestSuppressErrors:
	options:
		suppress runtime errors: true

	private unique_privateField: string
	public unique_stringField: string

	private unique_privateMethod():
		broadcast true

	public unique_stringArg(str: string):
		broadcast {_str}

test "ClassySK - Suppress Runtime Errors":
	set {_instance} to new instance of TestSuppressErrors

	catch runtime errors:
		set {_test} to {_instance}::unique_nonExistingField
		set {_test} to {_instance}::unique_privateField
		set {_instance}::unique_stringField to 1
		{_instance}::unique_privateMethod()
		{_instance}::unique_nonExistingMethod()
		{_instance}::unique_stringArg(true)

	assert last caught runtime errors is not set