class TypeA:
	public B_instance: TypeB instance

	public set(instance: TypeB instance):
		set self::B_instance to {_instance}

class TypeB:
	public A_instances: TypeA instances

	public setPlural(instances: TypeA instances):
		set {-typed::a::*} to {_instances::*}


local function test(a: TypeA instance, b: TypeB instance):
	set {-typed::a} to {_a}
	set {-typed::b} to {_b}

local function test1(a: TypeA instances):
	set {-typed::a::*} to {_a::*}

test "ClassySK - Types":

	set {_A} to new instance of TypeA
	set {_B} to new instance of TypeB

	set {_A}::B_instance to {_A}
	assert {_A}::B_instance is not set

	set {_A}::B_instance to {_B}
	assert {_A}::B_instance is set
	assert {_A}::B_instance is a TypeB instance

	delete {_A}::B_instance

	{_A}::set({_A})
	assert {_A}::B_instance is not set

	{_A}::set({_B})
	assert {_A}::B_instance is set
	assert {_A}::B_instance is a TypeB instance

	assert {_A}::B_instance is an instance of TypeB

	test({_B}, {_A})
	assert {-typed::a} is not set
	assert {-typed::b} is not set

	delete {-typed::*}
	test({_A}, {_A})
	assert {-typed::a} is set
	assert {-typed::b} is not set

	delete {-typed::*}
	test({_A}, {_B})
	assert {-typed::a} is set
	assert {-typed::b} is set

	test1(({_A}, {_A}, {_A}, {_B}))
	assert size of {-typed::a::*} is 3

	delete {-typed::a::*}
	{_B}::setPlural(({_A}, {_A}, {_B}, {_A}))
	assert size of {-typed::a::*} is 3

	set {_B}::A_instances to {_A}, {_A}, {_A}
	assert size of {_B}::A_instances is 3

	delete {_B}::A_instances
	set {_B}::A_instances to {_B}
	assert {_B}::A_instances is not set

	set {_B}::A_instances to {_A}, {_A}, {_B}, {_A}

	assert size of {_B}::A_instances is 3

class TestAssignability:

	public static chain(inst: TestAssignability instance):
		set {-TestAssignability} to {_inst}
		TestAssignability::chain1({_inst})

	public static chain1(inst: TestAssignAbilityFirst instance):
		set {-TestAssignability::chain::1} to {_inst}
		TestAssignability::chain2({_inst})

	public static chain2(inst: TestAssignAbilitySecond instance):
		set {-TestAssignability::chain::2} to {_inst}
		TestAssignability::chain3({_inst})

	public static chain3(inst: TestAssignAbilityThird instance):
		set {-TestAssignability::chain::3} to {_inst}

	
class AssignmentA:
	public a: int

class AssignmentB : AssignmentA:
	public a: int

class AssignmentC : AssignmentB:
	public a: int

class AssignmentD : AssignmentC:
	public a: int

local function downD(i: AssignmentD instance):
	add "D" to {-Assignment::down::*}
	downC({_i})
	
local function downC(i: AssignmentC instance):
	add "C" to {-Assignment::down::*}
	downB({_i})

local function downB(i: AssignmentB instance):
	add "B" to {-Assignment::down::*}
	downA({_i})

local function downA(i: AssignmentA instance):
	add "A" to {-Assignment::down::*}

# should work implicitly without type hints
local function upA(i: AssignmentA instance):
	add "A" to {-Assignment::up::*}
	upB({_i})

local function upB(i: AssignmentB instance):
	add "B" to {-Assignment::up::*}
	upC({_i})

local function upC(i: AssignmentC instance):
	add "C" to {-Assignment::up::*}
	upD({_i})

local function upD(i: AssignmentD instance):
	add "D" to {-Assignment::up::*}

test "ClassySK - Assignability (no type hints)":
	delete {-Assignment::*}

	set {_i} to new AssignmentD
	downD({_i})
	upD({_i})
	assert size of {-Assignment::down::*} is 4
	assert size of {-Assignment::up::*} is 1
	delete {-Assignment::*}

	set {_i} to new AssignmentC
	downC({_i})
	upC({_i})
	assert size of {-Assignment::down::*} is 3
	assert size of {-Assignment::up::*} is 2
	delete {-Assignment::*}

	set {_i} to new AssignmentB
	downB({_i})
	upB({_i})
	assert size of {-Assignment::down::*} is 2
	assert size of {-Assignment::up::*} is 3
	delete {-Assignment::*}

	set {_i} to new AssignmentA
	downA({_i})
	upA({_i})
	assert size of {-Assignment::down::*} is 1
	assert size of {-Assignment::up::*} is 4
	delete {-Assignment::*}

	set {_i} to new AssignmentA
	downB({_i})
	upB({_i})
	assert size of {-Assignment::down::*} is 0
	assert size of {-Assignment::up::*} is 0
	delete {-Assignment::*}