class TypeA:
	public B_instance: TypeB instance

	public set(instance: TypeB instance):
		set self::B_instance to {_instance}

class TypeB:
	public A_instances: TypeA instances

	public setPlural(instances: TypeA instances):
		set {-typed::a::*} to {_instances::*}


local function test(a: TypeA instance, b: TypeB instance):
	set {-typed::a} to {_a}
	set {-typed::b} to {_b}

local function test1(a: TypeA instances):
	set {-typed::a::*} to {_a::*}

test "ClassySK - Types":

	set {_A} to new instance of TypeA
	set {_B} to new instance of TypeB

	set {_A}::B_instance to {_A}
	assert {_A}::B_instance is not set

	set {_A}::B_instance to {_B}
	assert {_A}::B_instance is set
	assert {_A}::B_instance is a TypeB instance

	delete {_A}::B_instance

	{_A}::set({_A})
	assert {_A}::B_instance is not set

	{_A}::set({_B})
	assert {_A}::B_instance is set
	assert {_A}::B_instance is a TypeB instance

	assert {_A}::B_instance is an instance of TypeB

	test({_B}, {_A})
	assert {-typed::a} is not set
	assert {-typed::b} is not set

	delete {-typed::*}
	test({_A}, {_A})
	assert {-typed::a} is set
	assert {-typed::b} is not set

	delete {-typed::*}
	test({_A}, {_B})
	assert {-typed::a} is set
	assert {-typed::b} is set

	test1(({_A}, {_A}, {_A}, {_B}))
	assert size of {-typed::a::*} is 3

	delete {-typed::a::*}
	{_B}::setPlural(({_A}, {_A}, {_B}, {_A}))
	assert size of {-typed::a::*} is 3

	set {_B}::A_instances to {_A}, {_A}, {_A}
	assert size of {_B}::A_instances is 3

	delete {_B}::A_instances
	set {_B}::A_instances to {_B}
	assert {_B}::A_instances is not set

	set {_B}::A_instances to {_A}, {_A}, {_B}, {_A}

	assert size of {_B}::A_instances is 3