class TypeA:
	public B_instance: TypeB instance

	public set(instance: TypeB instance):
		set self::B_instance to {_instance}

class TypeB:
	public A_instances: TypeA instances

	public setPlural(instances: TypeA instances):
		set {-typed::a::*} to {_instances::*}


local function test(a: TypeA instance, b: TypeB instance):
	set {-typed::a} to {_a}
	set {-typed::b} to {_b}

local function test1(a: TypeA instances):
	set {-typed::a::*} to {_a::*}

test "ClassySK - Types":

	set {_A} to new instance of TypeA
	set {_B} to new instance of TypeB

	set {_A}::B_instance to {_A}
	assert {_A}::B_instance is not set

	set {_A}::B_instance to {_B}
	assert {_A}::B_instance is set
	assert {_A}::B_instance is a TypeB instance

	delete {_A}::B_instance

	{_A}::set({_A})
	assert {_A}::B_instance is not set

	{_A}::set({_B})
	assert {_A}::B_instance is set
	assert {_A}::B_instance is a TypeB instance

	assert {_A}::B_instance is an instance of TypeB

	test({_B}, {_A})
	assert {-typed::a} is not set
	assert {-typed::b} is not set

	delete {-typed::*}
	test({_A}, {_A})
	assert {-typed::a} is set
	assert {-typed::b} is not set

	delete {-typed::*}
	test({_A}, {_B})
	assert {-typed::a} is set
	assert {-typed::b} is set

	test1(({_A}, {_A}, {_A}, {_B}))
	assert size of {-typed::a::*} is 3

	delete {-typed::a::*}
	{_B}::setPlural(({_A}, {_A}, {_B}, {_A}))
	assert size of {-typed::a::*} is 3

	set {_B}::A_instances to {_A}, {_A}, {_A}
	assert size of {_B}::A_instances is 3

	delete {_B}::A_instances
	set {_B}::A_instances to {_B}
	assert {_B}::A_instances is not set

	set {_B}::A_instances to {_A}, {_A}, {_B}, {_A}

	assert size of {_B}::A_instances is 3

class TestAssignability:
	public static chainWithCast(inst: TestAssignability instance):
		TestAssignability::withCast1({_inst} as TestAssignAbilityFirst)

	public static withCast1(inst: TestAssignAbilityFirst instance):
		set {-TestAssignability::withCast::1} to {_inst}
		TestAssignability::withCast2({_inst} as TestAssignAbilitySecond)

	public static withCast2(inst: TestAssignAbilitySecond instance):
		set {-TestAssignability::withCast::2} to {_inst}
		TestAssignability::withCast3({_inst} as TestAssignAbilityThird)

	public static withCast3(inst: TestAssignAbilityThird instance):
		set {-TestAssignability::withCast::3} to {_inst}


	public static chainNoCast(inst: TestAssignability instance):
		set {-TestAssignability} to {_inst}
		TestAssignability::noCast1({_inst})

	public static noCast1(inst: TestAssignAbilityFirst instance):
		set {-TestAssignability::noCast::1} to {_inst}
		TestAssignability::noCast2({_inst})

	public static noCast2(inst: TestAssignAbilitySecond instance):
		set {-TestAssignability::noCast::2} to {_inst}
		TestAssignability::noCast3({_inst})

	public static noCast3(inst: TestAssignAbilityThird instance):
		set {-TestAssignability::noCast::3} to {_inst}

	

class TestAssignAbilityFirst extends TestAssignability:

class TestAssignAbilitySecond extends TestAssignAbilityFirst:

class TestAssignAbilityThird extends TestAssignAbilitySecond:

local function chainWithCast(inst: TestAssignability instance):
	withCast1({_inst} as TestAssignAbilityFirst)

local function withCast1(inst: TestAssignAbilityFirst instance):
	set {-TestAssignability::withCast::1} to {_inst}
	withCast2({_inst} as TestAssignAbilitySecond)

local function withCast2(inst: TestAssignAbilitySecond instance):
	set {-TestAssignability::withCast::2} to {_inst}
	withCast3({_inst} as TestAssignAbilityThird)

local function withCast3(inst: TestAssignAbilityThird instance):
	set {-TestAssignability::withCast::3} to {_inst}


local function chainNoCast(inst: TestAssignability instance):
	set {-TestAssignability} to {_inst}
	noCast1({_inst})

local function noCast1(inst: TestAssignAbilityFirst instance):
	set {-TestAssignability::noCast::1} to {_inst}
	noCast2({_inst})

local function noCast2(inst: TestAssignAbilitySecond instance):
	set {-TestAssignability::noCast::2} to {_inst}
	noCast3({_inst})

local function noCast3(inst: TestAssignAbilityThird instance):
	set {-TestAssignability::noCast::3} to {_inst}


test "ClassySK - upcast chain (functions)":
	delete {-TestAssignability::withCast::*}
	set {_inst} to new TestAssignAbilityThird

	chainWithCast({_inst})
	assert {-TestAssignability::withCast::1} is {_inst}
	assert {-TestAssignability::withCast::2} is {_inst}
	assert {-TestAssignability::withCast::3} is {_inst}

	delete {-TestAssignability::withCast::*}
	set {_inst} to new TestAssignAbilitySecond

	chainWithCast({_inst})
	assert {-TestAssignability::withCast::1} is {_inst}
	assert {-TestAssignability::withCast::2} is {_inst}
	assert {-TestAssignability::withCast::3} is not set

	delete {-TestAssignability::withCast::*}
	set {_inst} to new TestAssignAbilitySecond

	chainWithCast({_inst})
	assert {-TestAssignability::withCast::1} is {_inst}
	assert {-TestAssignability::withCast::2} is {_inst}
	assert {-TestAssignability::withCast::3} is not set

	delete {-TestAssignability::withCast::*}
	set {_inst} to new TestAssignAbilityFirst

	chainWithCast({_inst})
	assert {-TestAssignability::withCast::1} is {_inst}
	assert {-TestAssignability::withCast::2} is not set
	assert {-TestAssignability::withCast::3} is not set

	delete {-TestAssignability::withCast::*}
	set {_inst} to new TestAssignability

	chainWithCast({_inst})
	assert {-TestAssignability::withCast::1} is not set
	assert {-TestAssignability::withCast::2} is not set
	assert {-TestAssignability::withCast::3} is not set

test "ClassySK - no cast chain (functions)":
	delete {-TestAssignability::noCast::*}
	set {_inst} to new TestAssignAbilityThird

	chainNoCast({_inst})
	assert {-TestAssignability::noCast::1} is not set
	assert {-TestAssignability::noCast::2} is not set
	assert {-TestAssignability::noCast::3} is not set

	delete {-TestAssignability::noCast::*}
	set {_inst} to new TestAssignAbilitySecond

	chainNoCast({_inst})
	assert {-TestAssignability::noCast::1} is not set
	assert {-TestAssignability::noCast::2} is not set
	assert {-TestAssignability::noCast::3} is not set

	delete {-TestAssignability::noCast::*}
	set {_inst} to new TestAssignAbilitySecond

	chainNoCast({_inst})
	assert {-TestAssignability::noCast::1} is not set
	assert {-TestAssignability::noCast::2} is not set
	assert {-TestAssignability::noCast::3} is not set

	delete {-TestAssignability::noCast::*}
	set {_inst} to new TestAssignAbilityFirst

	chainNoCast({_inst})
	assert {-TestAssignability::noCast::1} is not set
	assert {-TestAssignability::noCast::2} is not set
	assert {-TestAssignability::noCast::3} is not set

	delete {-TestAssignability::noCast::*}
	set {_inst} to new TestAssignability

	chainNoCast({_inst})
	assert size of {-TestAssignability::noCast::*} is 0
	assert {-TestAssignability::noCast::1} is not set
	assert {-TestAssignability::noCast::2} is not set
	assert {-TestAssignability::noCast::3} is not set



test "ClassySK - upcast chain (methods)":
	delete {-TestAssignability::withCast::*}
	set {_inst} to new TestAssignAbilityThird

	TestAssignability::chainWithCast({_inst})
	assert {-TestAssignability::withCast::1} is {_inst}
	assert {-TestAssignability::withCast::2} is {_inst}
	assert {-TestAssignability::withCast::3} is {_inst}

	delete {-TestAssignability::withCast::*}
	set {_inst} to new TestAssignAbilitySecond

	TestAssignability::chainWithCast({_inst})
	assert {-TestAssignability::withCast::1} is {_inst}
	assert {-TestAssignability::withCast::2} is {_inst}
	assert {-TestAssignability::withCast::3} is not set

	delete {-TestAssignability::withCast::*}
	set {_inst} to new TestAssignAbilitySecond

	TestAssignability::chainWithCast({_inst})
	assert {-TestAssignability::withCast::1} is {_inst}
	assert {-TestAssignability::withCast::2} is {_inst}
	assert {-TestAssignability::withCast::3} is not set

	delete {-TestAssignability::withCast::*}
	set {_inst} to new TestAssignAbilityFirst

	TestAssignability::chainWithCast({_inst})
	assert {-TestAssignability::withCast::1} is {_inst}
	assert {-TestAssignability::withCast::2} is not set
	assert {-TestAssignability::withCast::3} is not set

	delete {-TestAssignability::withCast::*}
	set {_inst} to new TestAssignability

	TestAssignability::chainWithCast({_inst})
	assert {-TestAssignability::withCast::1} is not set
	assert {-TestAssignability::withCast::2} is not set
	assert {-TestAssignability::withCast::3} is not set

test "ClassySK - no cast chain (methods)":
	delete {-TestAssignability::noCast::*}
	set {_inst} to new TestAssignAbilityThird

	TestAssignability::chainNoCast({_inst})
	assert {-TestAssignability::noCast::1} is not set
	assert {-TestAssignability::noCast::2} is not set
	assert {-TestAssignability::noCast::3} is not set

	delete {-TestAssignability::noCast::*}
	set {_inst} to new TestAssignAbilitySecond

	TestAssignability::chainNoCast({_inst})
	assert {-TestAssignability::noCast::1} is not set
	assert {-TestAssignability::noCast::2} is not set
	assert {-TestAssignability::noCast::3} is not set

	delete {-TestAssignability::noCast::*}
	set {_inst} to new TestAssignAbilitySecond

	TestAssignability::chainNoCast({_inst})
	assert {-TestAssignability::noCast::1} is not set
	assert {-TestAssignability::noCast::2} is not set
	assert {-TestAssignability::noCast::3} is not set

	delete {-TestAssignability::noCast::*}
	set {_inst} to new TestAssignAbilityFirst

	TestAssignability::chainNoCast({_inst})
	assert {-TestAssignability::noCast::1} is not set
	assert {-TestAssignability::noCast::2} is not set
	assert {-TestAssignability::noCast::3} is not set

	delete {-TestAssignability::noCast::*}
	set {_inst} to new TestAssignability

	TestAssignability::chainNoCast({_inst})
	assert size of {-TestAssignability::noCast::*} is 0
	assert {-TestAssignability::noCast::1} is not set
	assert {-TestAssignability::noCast::2} is not set
	assert {-TestAssignability::noCast::3} is not set