name: nightly release

on:
  workflow_dispatch:


jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Create nightly release
        id: create_release
        uses: viperproject/create-nightly-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Nightly Release ${{ env.TAG_NAME }}
          keep_num: 0
          keep_tags: false